Change commit-from-anon-repo to report an error on exit
This makes it possible to tell if anything went wrong during operation
without having to check potentially thousands of lines of log messages.

diff --git a/commit-from-anon-repo b/commit-from-anon-repo
--- a/commit-from-anon-repo
+++ b/commit-from-anon-repo
@@ -16,17 +16,25 @@ shift
 COMMENT="$1"
 shift
 
+# Holds the last file that caused an error
+FAILFILE=
+
 for f in "$@"; do
     case "$f" in
         /*) D="$(dirname "$f")";;               # absolute path
         *) D="$(readlink -f "$SPEC_TREE/$f")";; # bare repo name
     esac
     echo "$D"
-    cd "$D" || { echo Error: could not cd "$D"; continue; }
+    cd "$D" || {
+        echo Error: could not cd "$D";
+        FAILFILE="$f"
+        continue;
+    }
     OLDU="$(svn info --show-item url)"
     NEWU="$(sed 's/^svn:/svn+ssh:/' <<<"$OLDU")"
     if [[ -z "$OLDU" || "$OLDU" == "$NEWU" ]]; then
         echo Error: URL could not be converted at "$D" 1>&2
+        FAILFILE="$f"
     else
         if svn relocate "$OLDU" "$NEWU" &&
             svn ci -m "${COMMENT}"; then
@@ -36,7 +44,12 @@ for f in "$@"; do
         else
             # Failed submission; clean up only
             echo Failed svn commit 1>&2
+            FAILFILE="$f"
             svn relocate "$NEWU" "$OLDU"
         fi
     fi
 done
+if [[ -n "$FAILFILE" ]]; then
+    echo "Error: at least one error occurred, most recently for $FAILFILE" 1>&2
+    exit 1
+fi
